# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "types.Request" do
    oneof :value do
      optional :echo, :message, 1, "types.RequestEcho"
      optional :flush, :message, 2, "types.RequestFlush"
      optional :info, :message, 3, "types.RequestInfo"
      optional :set_option, :message, 4, "types.RequestSetOption"
      optional :deliver_tx, :message, 5, "types.RequestDeliverTx"
      optional :check_tx, :message, 6, "types.RequestCheckTx"
      optional :commit, :message, 7, "types.RequestCommit"
      optional :query, :message, 8, "types.RequestQuery"
      optional :init_chain, :message, 9, "types.RequestInitChain"
      optional :begin_block, :message, 10, "types.RequestBeginBlock"
      optional :end_block, :message, 11, "types.RequestEndBlock"
    end
  end
  add_message "types.RequestEcho" do
    optional :message, :string, 1
  end
  add_message "types.RequestFlush" do
  end
  add_message "types.RequestInfo" do
  end
  add_message "types.RequestSetOption" do
    optional :key, :string, 1
    optional :value, :string, 2
  end
  add_message "types.RequestDeliverTx" do
    optional :tx, :bytes, 1
  end
  add_message "types.RequestCheckTx" do
    optional :tx, :bytes, 1
  end
  add_message "types.RequestQuery" do
    optional :data, :bytes, 1
    optional :path, :string, 2
    optional :height, :uint64, 3
    optional :prove, :bool, 4
  end
  add_message "types.RequestCommit" do
  end
  add_message "types.RequestInitChain" do
    repeated :validators, :message, 1, "types.Validator"
  end
  add_message "types.RequestBeginBlock" do
    optional :hash, :bytes, 1
    optional :header, :message, 2, "types.Header"
  end
  add_message "types.RequestEndBlock" do
    optional :height, :uint64, 1
  end
  add_message "types.Response" do
    oneof :value do
      optional :exception, :message, 1, "types.ResponseException"
      optional :echo, :message, 2, "types.ResponseEcho"
      optional :flush, :message, 3, "types.ResponseFlush"
      optional :info, :message, 4, "types.ResponseInfo"
      optional :set_option, :message, 5, "types.ResponseSetOption"
      optional :deliver_tx, :message, 6, "types.ResponseDeliverTx"
      optional :check_tx, :message, 7, "types.ResponseCheckTx"
      optional :commit, :message, 8, "types.ResponseCommit"
      optional :query, :message, 9, "types.ResponseQuery"
      optional :init_chain, :message, 10, "types.ResponseInitChain"
      optional :begin_block, :message, 11, "types.ResponseBeginBlock"
      optional :end_block, :message, 12, "types.ResponseEndBlock"
    end
  end
  add_message "types.ResponseException" do
    optional :error, :string, 1
  end
  add_message "types.ResponseEcho" do
    optional :message, :string, 1
  end
  add_message "types.ResponseFlush" do
  end
  add_message "types.ResponseInfo" do
    optional :data, :string, 1
    optional :version, :string, 2
    optional :last_block_height, :uint64, 3
    optional :last_block_app_hash, :bytes, 4
  end
  add_message "types.ResponseSetOption" do
    optional :log, :string, 1
  end
  add_message "types.ResponseDeliverTx" do
    optional :code, :enum, 1, "types.CodeType"
    optional :data, :bytes, 2
    optional :log, :string, 3
  end
  add_message "types.ResponseCheckTx" do
    optional :code, :enum, 1, "types.CodeType"
    optional :data, :bytes, 2
    optional :log, :string, 3
  end
  add_message "types.ResponseQuery" do
    optional :code, :enum, 1, "types.CodeType"
    optional :index, :int64, 2
    optional :key, :bytes, 3
    optional :value, :bytes, 4
    optional :proof, :bytes, 5
    optional :height, :uint64, 6
    optional :log, :string, 7
  end
  add_message "types.ResponseCommit" do
    optional :code, :enum, 1, "types.CodeType"
    optional :data, :bytes, 2
    optional :log, :string, 3
  end
  add_message "types.ResponseInitChain" do
  end
  add_message "types.ResponseBeginBlock" do
  end
  add_message "types.ResponseEndBlock" do
    repeated :diffs, :message, 1, "types.Validator"
  end
  add_message "types.Header" do
    optional :chain_id, :string, 1
    optional :height, :uint64, 2
    optional :time, :uint64, 3
    optional :num_txs, :uint64, 4
    optional :last_block_id, :message, 5, "types.BlockID"
    optional :last_commit_hash, :bytes, 6
    optional :data_hash, :bytes, 7
    optional :validators_hash, :bytes, 8
    optional :app_hash, :bytes, 9
  end
  add_message "types.BlockID" do
    optional :hash, :bytes, 1
    optional :parts, :message, 2, "types.PartSetHeader"
  end
  add_message "types.PartSetHeader" do
    optional :total, :uint64, 1
    optional :hash, :bytes, 2
  end
  add_message "types.Validator" do
    optional :pubKey, :bytes, 1
    optional :power, :uint64, 2
  end
  add_enum "types.MessageType" do
    value :NullMessage, 0
    value :Echo, 1
    value :Flush, 2
    value :Info, 3
    value :SetOption, 4
    value :Exception, 5
    value :DeliverTx, 17
    value :CheckTx, 18
    value :Commit, 19
    value :Query, 20
    value :InitChain, 21
    value :BeginBlock, 22
    value :EndBlock, 23
  end
  add_enum "types.CodeType" do
    value :OK, 0
    value :InternalError, 1
    value :EncodingError, 2
    value :BadNonce, 3
    value :Unauthorized, 4
    value :InsufficientFunds, 5
    value :UnknownRequest, 6
    value :BaseDuplicateAddress, 101
    value :BaseEncodingError, 102
    value :BaseInsufficientFees, 103
    value :BaseInsufficientFunds, 104
    value :BaseInsufficientGasPrice, 105
    value :BaseInvalidInput, 106
    value :BaseInvalidOutput, 107
    value :BaseInvalidPubKey, 108
    value :BaseInvalidSequence, 109
    value :BaseInvalidSignature, 110
    value :BaseUnknownAddress, 111
    value :BaseUnknownPubKey, 112
    value :BaseUnknownPlugin, 113
    value :GovUnknownEntity, 201
    value :GovUnknownGroup, 202
    value :GovUnknownProposal, 203
    value :GovDuplicateGroup, 204
    value :GovDuplicateMember, 205
    value :GovDuplicateProposal, 206
    value :GovDuplicateVote, 207
    value :GovInvalidMember, 208
    value :GovInvalidVote, 209
    value :GovInvalidVotingPower, 210
  end
end

module Types
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.Request").msgclass
  RequestEcho = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestEcho").msgclass
  RequestFlush = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestFlush").msgclass
  RequestInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestInfo").msgclass
  RequestSetOption = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestSetOption").msgclass
  RequestDeliverTx = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestDeliverTx").msgclass
  RequestCheckTx = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestCheckTx").msgclass
  RequestQuery = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestQuery").msgclass
  RequestCommit = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestCommit").msgclass
  RequestInitChain = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestInitChain").msgclass
  RequestBeginBlock = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestBeginBlock").msgclass
  RequestEndBlock = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestEndBlock").msgclass
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.Response").msgclass
  ResponseException = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseException").msgclass
  ResponseEcho = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseEcho").msgclass
  ResponseFlush = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseFlush").msgclass
  ResponseInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseInfo").msgclass
  ResponseSetOption = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseSetOption").msgclass
  ResponseDeliverTx = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseDeliverTx").msgclass
  ResponseCheckTx = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseCheckTx").msgclass
  ResponseQuery = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseQuery").msgclass
  ResponseCommit = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseCommit").msgclass
  ResponseInitChain = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseInitChain").msgclass
  ResponseBeginBlock = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseBeginBlock").msgclass
  ResponseEndBlock = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseEndBlock").msgclass
  Header = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.Header").msgclass
  BlockID = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.BlockID").msgclass
  PartSetHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.PartSetHeader").msgclass
  Validator = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.Validator").msgclass
  MessageType = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.MessageType").enummodule
  CodeType = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.CodeType").enummodule
end
